# Generated by Django 4.1.3 on 2023-02-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitati', '0002_invitati_invitatidelamasa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitati',
            name='invitatidelamasa',
        ),
    ]
