# Generated by Django 4.1.3 on 2023-02-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitati', '0003_remove_invitati_invitatidelamasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitati',
            name='check_in',
            field=models.BooleanField(default=False),
        ),
    ]
